[package]
name = "hextergen"
version = "0.1.0"
edition = "2021"

[dependencies]
argh = "0.1.12"
env_logger = "0.11.3"
hexx = "0.15.0"
image = "0.25.0"
imageproc = "0.24.0"
log = "0.4.21"
ndarray = { version = "0.15.6", features = ["rayon"] }
rayon = "1.9.0"
